var myLogModule = require('./Log.js');
myLogModule.info('Node.js started');
var msg=require('./Message.js');
console.log(msg.SimpleMessgae);
var msg=require('./Log.js');
msg.log('Hello World');
var person = require('./data.js');
console.log(person.firstName + ' ' + person.lastName);
var person = require('./Person.js');
var person1 = new person('james', 'Bond');
console.log(person1.fullName());